// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsUukJ9hIBG9Na5Qlp-IgAZTSkx8VJY5s',
    appId: '1:250762180114:web:dc2ca80ee811fdced3cacb',
    messagingSenderId: '250762180114',
    projectId: 'latihannnn-fae7d',
    authDomain: 'latihannnn-fae7d.firebaseapp.com',
    storageBucket: 'latihannnn-fae7d.firebasestorage.app',
    measurementId: 'G-LJR1THT4QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2Gyx4tB_HL01g6fZJk82xKQQnXDJJZ8',
    appId: '1:250762180114:android:6272646647cd12bdd3cacb',
    messagingSenderId: '250762180114',
    projectId: 'latihannnn-fae7d',
    storageBucket: 'latihannnn-fae7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCcTQL7OX0Kqa_QxoKaI3xEZIRqDHybec',
    appId: '1:250762180114:ios:98670ff1c8937903d3cacb',
    messagingSenderId: '250762180114',
    projectId: 'latihannnn-fae7d',
    storageBucket: 'latihannnn-fae7d.firebasestorage.app',
    iosBundleId: 'com.example.notess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCcTQL7OX0Kqa_QxoKaI3xEZIRqDHybec',
    appId: '1:250762180114:ios:98670ff1c8937903d3cacb',
    messagingSenderId: '250762180114',
    projectId: 'latihannnn-fae7d',
    storageBucket: 'latihannnn-fae7d.firebasestorage.app',
    iosBundleId: 'com.example.notess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsUukJ9hIBG9Na5Qlp-IgAZTSkx8VJY5s',
    appId: '1:250762180114:web:9a8f9bf801cfda6ed3cacb',
    messagingSenderId: '250762180114',
    projectId: 'latihannnn-fae7d',
    authDomain: 'latihannnn-fae7d.firebaseapp.com',
    storageBucket: 'latihannnn-fae7d.firebasestorage.app',
    measurementId: 'G-YRN5866J5F',
  );

}